### ISSUE TITLE
Coverage not at 100%

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/phoenix-todo-list-tutorial#65]
Although this will be fixed with #56 and #60 when merged, the current coverage of this repo is **not at 100%**. 
This is the last CI run:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/17494745/208661989-257ef989-7f40-4c08-8cb6-b34b38cc6e65.png">

This was weird because Codecov shows it's at 100%.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/17494745/208662128-c08ab6ac-8472-4f86-acf3-19e966b06b3f.png">

**Comment by nelsonic** [comment]
Sadly, the `Auth` PR #56 does not have **`100%`** coverage at the time of writing 
[otherwise it would be a _lot_ easier for me to review + merge ...] : 
https://github.com/dwyl/phoenix-todo-list-tutorial/pull/56#issuecomment-1346223411
<img width="924" alt="image" src="https://user-images.githubusercontent.com/194400/208820296-a56ac4ba-16c1-4c52-af96-33f3a83598d4.png">

The line in the `lib/app_web/controllers/item_controller.ex` file that does not have coverage is:
<img width="1007" alt="phoenix-todo-list-tutorial-not-covered-line" src="https://user-images.githubusercontent.com/194400/208820640-68433d19-cfab-4375-9252-940204350ede.png">

https://github.com/dwyl/phoenix-todo-list-tutorial/blob/1ac2772e8b2c833f658d4eadd52e07d735a9865f/lib/app_web/controllers/item_controller.ex#L115

I've tried simply adding an `assign` in the test:

```elixir
conn = conn
  |> assign(:loggedin, true)
  |> assign(:person, %{id: 42, givenName: "Alex McAwesome"})
  |> get(~p"/items/clear")
```

But this doesn't appear to work ...

**Comment by nelsonic** [comment]
Ah ... muuuuch better. 😊 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/194400/208826624-271272e1-0e7a-4196-a732-ba28655bb39c.png">

**Comment by nelsonic** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/194400/209737936-993d61a5-8e99-4484-af8a-82f99e5ad117.png">

![codecov.io](https://img.shields.io/codecov/c/github/dwyl/phoenix-todo-list-tutorial/master.svg?style=flat-square)

buuuuttt .... the badge is for `master`:

```sh
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/phoenix-todo-list-tutorial/master.svg?style=flat-square)]
```

and should instead be for `main`:

```
![codecov.io](https://img.shields.io/codecov/c/github/dwyl/phoenix-todo-list-tutorial/main.svg?style=flat-square)
```

![codecov.io](https://img.shields.io/codecov/c/github/dwyl/phoenix-todo-list-tutorial/main.svg?style=flat-square)
